### ISSUE TITLE
学生部のサイトを一新する件

### ISSUE THREAD

**Issue by lrf141** [local-students/local-students.github.io#32]
# 学生部のサイトを一新したい

- 学生部のサイトが古いままなのをどうにかしたい
- 特にトップページの画像
- もっといい感じのあれこれに載せたい
- さくらのサーバが使えるかもしれない

**Comment by chikuwait** [comment]
- 現状はjekyll + github pagesで作成されている
- Blogの更新が主体ならワードプレスやCMSに移行してしまったほうが管理が楽かもしれない

**Comment by w-haibara** [comment]
以下のissueに分割．
#40 #41 #42
