### ISSUE TITLE
jekyllのいい感じのテーマを探す

### ISSUE THREAD

**Issue by chikuwait** [local-students/local-students.github.io#33]

**Comment by GunjiD** [comment]
これとかどうですかね
http://jekyllthemes.org/themes/TeXt/

**Comment by chikuwait** [comment]
- [Jekyll Materialize](http://jekyllmaterialize.panoramedia.it/)
- [Event](http://jekyllthemes.org/themes/event-jekyll-theme/)

**Comment by GunjiD** [comment]
http://jekyllthemes.org/themes/fresh/

**Comment by GunjiD** [comment]
http://jekyllthemes.org/themes/textlog/

**Comment by lrf141** [comment]
https://hemangsk.github.io/DevJournal/

**Comment by lrf141** [comment]
https://le4ker.github.io/personal-jekyll-theme/

**Comment by GunjiD** [comment]
https://karloespiritu.com/blackdoc/

**Comment by lrf141** [comment]
これでいく
https://chrisbobbe.github.io/jekyll-theme-prologue/
